#!/usr/bin/env python3
"""Generate src/assets/classes.js and src/assets/resources.js from a Diamond Rush JAR.

Usage:
    python3 tools/build_assets.py [--jar 钻石狂潮.jar] [--out src/assets]

The JAR is not part of this repository; provide your own legally obtained copy.
"""
import argparse
import base64
import json
import os
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--jar', default=os.environ.get('DR_JAR', os.path.join(ROOT, '钻石狂潮.jar')))
    ap.add_argument('--out', default=os.path.join(ROOT, 'src', 'assets'))
    args = ap.parse_args()

    if not os.path.isfile(args.jar):
        raise SystemExit('JAR not found: %s\nPut your own Diamond Rush JAR there or pass --jar <path>' % args.jar)

    os.makedirs(args.out, exist_ok=True)
    z = zipfile.ZipFile(args.jar)
    classes = {}
    resources = {}
    for n in z.namelist():
        if n.endswith('/'):
            continue
        data = z.read(n)
        if n.endswith('.class'):
            classes[n[:-6]] = base64.b64encode(data).decode('ascii')
        else:
            if n.startswith('META-INF') and not n.endswith('MANIFEST.MF'):
                continue
            resources[n] = base64.b64encode(data).decode('ascii')

    with open(os.path.join(args.out, 'classes.js'), 'w') as f:
        f.write('// generated by tools/build_assets.py -- do not edit\n')
        f.write('var VM_CLASSES = ' + json.dumps(classes, separators=(',', ':')) + ';\n')

    with open(os.path.join(args.out, 'resources.js'), 'w') as f:
        f.write('// generated by tools/build_assets.py -- do not edit\n')
        f.write('var VM_RESOURCES = ' + json.dumps(resources, separators=(',', ':')) + ';\n')
    print('classes: %d, resources: %d -> %s' % (len(classes), len(resources), args.out))


if __name__ == '__main__':
    main()
