#!/usr/bin/env python3
"""Generate the asset bundles for the portrait and landscape game versions.

Usage:
    # both versions (recommended): portrait = original, landscape = Diamond_CP
    python3 tools/build_assets.py --portrait 钻石狂潮.jar --landscape diamond_CP.jar

    # portrait only (landscape toggle is hidden in the app)
    python3 tools/build_assets.py --portrait 钻石狂潮.jar

Output (into --out, default src/assets):
    classes.p.js     VM_CLASSES_P     portrait bytecode
    classes.l.js     VM_CLASSES_L     landscape bytecode (if provided)
    resources.js     VM_RESOURCES     resources identical in both versions
    resources.p.js   VM_RESOURCES_P   portrait-only / portrait-specific resources
    resources.l.js   VM_RESOURCES_L   landscape-only / landscape-specific resources

The JARs are not part of this repository; provide your own legally obtained copies.
"""
import argparse
import base64
import json
import os
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def read_jar(path):
    z = zipfile.ZipFile(path)
    classes = {}
    resources = {}
    for n in z.namelist():
        if n.endswith('/'):
            continue
        data = z.read(n)
        if n.endswith('.class'):
            classes[n[:-6]] = base64.b64encode(data).decode('ascii')
        else:
            if n.startswith('META-INF') and not n.endswith('MANIFEST.MF'):
                continue
            resources[n] = base64.b64encode(data).decode('ascii')
    return classes, resources


def write_var(path, name, obj):
    with open(path, 'w') as f:
        f.write('// generated by tools/build_assets.py -- do not edit\n')
        f.write('var %s = %s;\n' % (name, json.dumps(obj, separators=(',', ':'))))
    return os.path.getsize(path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--jar', dest='portrait', default=None,
                    help='portrait JAR (alias of --portrait)')
    ap.add_argument('--portrait', dest='portrait2', default=None,
                    help='portrait JAR (default: DR_JAR or 钻石狂潮.jar)')
    ap.add_argument('--landscape', default=None,
                    help='landscape JAR (default: diamond_CP.jar if present)')
    ap.add_argument('--out', default=os.path.join(ROOT, 'src', 'assets'))
    args = ap.parse_args()

    p_jar = args.portrait2 or args.portrait or os.environ.get('DR_JAR') or os.path.join(ROOT, '钻石狂潮.jar')
    l_jar = args.landscape
    if l_jar is None:
        candidate = os.path.join(ROOT, 'diamond_CP.jar')
        if os.path.isfile(candidate):
            l_jar = candidate
    if not os.path.isfile(p_jar):
        raise SystemExit('portrait JAR not found: %s' % p_jar)
    if l_jar is not None and not os.path.isfile(l_jar):
        raise SystemExit('landscape JAR not found: %s' % l_jar)

    os.makedirs(args.out, exist_ok=True)
    p_classes, p_res = read_jar(p_jar)
    l_classes, l_res = read_jar(l_jar) if l_jar else ({}, {})

    shared = {k: v for k, v in p_res.items() if k in l_res and l_res[k] == v}
    p_only = {k: v for k, v in p_res.items() if k not in shared}
    l_only = {k: v for k, v in l_res.items() if k not in shared} if l_jar else {}

    write_var(os.path.join(args.out, 'classes.p.js'), 'VM_CLASSES_P', p_classes)
    write_var(os.path.join(args.out, 'resources.js'), 'VM_RESOURCES', shared)
    write_var(os.path.join(args.out, 'resources.p.js'), 'VM_RESOURCES_P', p_only)
    lines = ['classes.p: %d, shared: %d, portrait-only: %d' % (len(p_classes), len(shared), len(p_only))]
    if l_jar:
        write_var(os.path.join(args.out, 'classes.l.js'), 'VM_CLASSES_L', l_classes)
        write_var(os.path.join(args.out, 'resources.l.js'), 'VM_RESOURCES_L', l_only)
        lines.append('classes.l: %d, landscape-only: %d' % (len(l_classes), len(l_only)))
    else:
        for f in ('classes.l.js', 'resources.l.js'):
            try:
                os.remove(os.path.join(args.out, f))
            except OSError:
                pass
    print(', '.join(lines) + ' -> ' + args.out)


if __name__ == '__main__':
    main()
